name: Luacheck

on: [push, pull_request]

jobs:

  luacheck:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Lua
      uses: leafo/gh-actions-lua@v8
    - name: Setup Luarocks
      uses: leafo/gh-actions-luarocks@v4
    - name: Install luacheck
      run: luarocks install luacheck
    - name: Lint all the Lua code
      run: luacheck .
